title: O Bolo da Ivone
email: contato@bolodaivone.com.br
description: >
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, 
  sed diam nonummy nibh euismod tincidunt ut laoreet dolore 
  magna aliquam erat volutpat. Ut wisi enim ad minim veniam, 
  quis nostrud exerci tation ullamcorper suscipit lobortis.
baseurl: ""
url: "http://bolodaivone.com.br"

markdown: kramdown

sass:
    style: compressed

port: 3000
